name: neuro_wood
description: A new Flutter project.

publish_to: "none"

version: 0.4.4+42

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  cloud_functions: ^5.5.1
  firebase_crashlytics: ^4.3.6
  firebase_app_check: ^0.3.2+6
  #DI
  get_it: ^8.0.3
  #state managment
  flutter_bloc: ^9.1.1
  rxdart: ^0.28.0
  dartz: ^0.10.1
  #helpers
  freezed_annotation: ^3.0.0
  json_serializable: ^6.9.5
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  go_router: ^15.2.0
  easy_localization: ^3.0.7+1
  collection: ^1.19.1
  #ui
  extended_masked_text: ^3.0.1
  flutter_keyboard_visibility: ^6.0.0
  # webview_flutter: ^4.13.0
  snapping_sheet: ^3.1.0
  carousel_slider: ^5.0.0
  # flutter_svg: ^2.1.0
  intl: ^0.20.2
  #feature
  appmetrica_plugin: ^3.2.0
  permission_handler: ^12.0.0+1
  camera: ^0.11.1
  image_picker: ^1.1.2
  pdfrx: ^1.2.1
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  sensors_plus: ^6.1.1
  store_redirect: ^2.0.4
  wakelock_plus: ^1.3.2
  pdf: ^3.11.3
  image: ^4.5.4
  share_plus: ^11.0.0
  flutter_file_dialog: ^3.0.2
  shared_preferences: ^2.5.3
  # wakelock_web: ^0.4.0
  flutter_image_compress: ^2.4.0
  mytracker_sdk:
    path: ./3rd_party/mytracker_sdk-3.1.1/

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^3.0.6
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/app_icon_android.png"
  image_path_ios: "assets/app_icon/app_icon_ios.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_icon/app_icon_white_fg.png"

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: NeuroWood
      fonts:
        - asset: assets/fonts/NeuroWood.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/static/OpenSans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Open_Sans/static/OpenSans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Open_Sans/static/OpenSans/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Open_Sans/static/OpenSans/OpenSans-SemiBold.ttf
          weight: 600

  assets:
    - assets/images/
    - assets/images/stories/
    - assets/translations/
    - assets/docs/
    - assets/fonts/Open_Sans/static/OpenSans/OpenSans-Regular.ttf
    - assets/fonts/Open_Sans/static/OpenSans/OpenSans-SemiBold.ttf
