/* Flutter icons NeuroWood
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NeuroWood
///      fonts:
///       - asset: fonts/NeuroWood.ttf
///
///
///
// ignore_for_file: constant_identifier_names
*/

import 'package:flutter/widgets.dart';

class NeuroWoodIcons {
  NeuroWoodIcons._();

  static const _kFontFam = 'NeuroWood';
  static const String? _kFontPkg = null;

  static const IconData arrowLeft = IconData(
    0xe800,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData arrowRight = IconData(
    0xe801,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData camera = IconData(
    0xe802,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData logo = IconData(
    0xe803,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData close = IconData(
    0xe804,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData arrowDown = IconData(
    0xe805,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ruler = IconData(
    0xe808,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData user = IconData(
    0xe80a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData download = IconData(
    0xe80b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData edit = IconData(
    0xe80c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData image = IconData(
    0xe80d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData logout = IconData(
    0xe80e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData share = IconData(
    0xe80f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
}
